#!/bin/bash
modname=vua-srl-nl
#
# Find the path to this module
#
if
  [ -z ${MODROOT+x} ]
then
  # Find out path ourselves
  thisdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"
else
  thisdir=$MODROOT/$modname
fi
thisscript=${thisdir}/run
# Expects that command "timbl" works
cd $thisdir
tempdir=`mktemp -d -t SRLTMP.XXXXXX`
inputfile=$tempdir/inputfile
featurevector=$tempdir/csvfile
timbloutputfile=$tempdir/timblpredictions
cat | tee  $inputfile | python nafAlpinoToSRLFeatures.py > $featurevector
timbl -mO:I1,2,3,4 -i 25Feb2015_e-mags_mags_press_newspapers.wgt -t $featurevector -o $timbloutputfile >/dev/null 2>/dev/null
python timblToAlpinoNAF.py $inputfile $timbloutputfile
rm -rf $tempdir
